pipeline {
    agent any

    parameters {
        string(
            name: 'NUMBERS',
            defaultValue: '10 20 30',
            description: 'Enter numbers separated by spaces'
        )
    }

    stages {

        stage('Run Application') {
            steps {
                dir('project1') {
                    sh """
                    python3 sum_numbers.py ${params.NUMBERS}
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Application deployed successfully'
            }
        }
    }
}