pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Files') {
            steps {
                sh '''
                pwd
                ls -R
                '''
            }
        }

        stage('Docker Check') {
            steps {
                sh '''
                docker --version
                docker compose version || true
                docker-compose --version || true
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('project2/form-app') {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Deploy Application') {
            steps {
                dir('project2/form-app') {
                    sh '''
                    docker-compose down || true
                    docker-compose up -d
                    '''
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                docker ps
                '''
            }
        }
    }

    post {

        success {
            echo 'Application deployed successfully'
        }

        failure {
            echo 'Deployment failed'
        }
    }
}